tags:
  - name: characters
    description: characters API
  - name: clans
    description: clans API
  - name: akatsuki
    description: akatsuki API
  - name: kara
    description: kara API
  - name: tailedbeasts
    description: tailedbeasts API
  - name: teams
    description: teams API
  - name: villages
    description: villages API
  - name: kekkeigenkai
    description: kekkeigenkai API

paths:
  # [GET] all characters
  /character:
    get:
      tags:
        - characters
      summary: Get all characters
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of characters
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] character by id
  /character/{id}:
    get:
      tags:
        - characters
      summary: Get character by id
      parameters:
        - name: id
          in: path
          description: character id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search character
  /character/search:
    get:
      tags:
        - characters
      summary: Search character
      parameters:
        - name: name
          in: query
          description: character name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all clans
  /clan:
    get:
      tags:
        - clans
      summary: Get all clans
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of clans
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] clan by id
  /clan/{id}:
    get:
      tags:
        - clans
      summary: Get clan by id
      parameters:
        - name: id
          in: path
          description: clan id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search clan
  /clan/search:
    get:
      tags:
        - clans
      summary: Search clan
      parameters:
        - name: name
          in: query
          description: clan name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all akatsuki members
  /akatsuki:
    get:
      tags:
        - akatsuki
      summary: Get all akatsuki members
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of akatsuki members
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] akatsuki member by id
  /akatsuki/{id}:
    get:
      tags:
        - akatsuki
      summary: Get akatsuki member by id
      parameters:
        - name: id
          in: path
          description: akatsuki id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search akatsuki member
  /akatsuki/search:
    get:
      tags:
        - akatsuki
      summary: Search akatsuki member
      parameters:
        - name: name
          in: query
          description: akatsuki member name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all kara members
  /kara:
    get:
      tags:
        - kara
      summary: Get all kara members
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of kara members
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] kara member by id
  /kara/{id}:
    get:
      tags:
        - kara
      summary: Get kara member by id
      parameters:
        - name: id
          in: path
          description: kara id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search kara member
  /kara/search:
    get:
      tags:
        - kara
      summary: Search kara member
      parameters:
        - name: name
          in: query
          description: kara member name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all villages
  /village:
    get:
      tags:
        - villages
      summary: Get all villages
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of villages
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] village by id
  /village/{id}:
    get:
      tags:
        - villages
      summary: Get village by id
      parameters:
        - name: id
          in: path
          description: village id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search village
  /village/search:
    get:
      tags:
        - villages
      summary: Search village
      parameters:
        - name: name
          in: query
          description: village name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all teams
  /team:
    get:
      tags:
        - teams
      summary: Get all teams
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of teams
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] team by id
  /team/{id}:
    get:
      tags:
        - teams
      summary: Get team by id
      parameters:
        - name: id
          in: path
          description: team id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search team
  /team/search:
    get:
      tags:
        - teams
      summary: Search team
      parameters:
        - name: name
          in: query
          description: team name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all tailed beasts
  /tailed-beast:
    get:
      tags:
        - tailed-beasts
      summary: Get all tailed beasts
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of tailed beasts
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] tailed beast by id
  /tailed-beast/{id}:
    get:
      tags:
        - tailed-beasts
      summary: Get tailed beast by id
      parameters:
        - name: id
          in: path
          description: tailed beast id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search tailed beast
  /tailed-beast/search:
    get:
      tags:
        - tailed-beasts
      summary: Search tailed beast
      parameters:
        - name: name
          in: query
          description: tailed beast name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all kekkei genkai
  /kekkei-genkai:
    get:
      tags:
        - kekkei-genkai
      summary: Get all kekkei genkai
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of kekkei genkai
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] kekkei genkai by id
  /kekkei-genkai/{id}:
    get:
      tags:
        - kekkei-genkai
      summary: Get kekkei genkai by id
      parameters:
        - name: id
          in: path
          description: kekkei genkai id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search kekkei genkai
  /kekkei-genkai/search:
    get:
      tags:
        - kekkei-genkai
      summary: Search kekkei genkai
      parameters:
        - name: name
          in: query
          description: kekkei genkai name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
