tags:
  - name: characters
    description: characters API

paths:
  # [GET] all characters
  /character:
    get:
      tags:
        - characters
      summary: Get all characters
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of characters
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] character by id
  /character/{id}:
    get:
      tags:
        - characters
      summary: Get character by id
      parameters:
        - name: id
          in: path
          description: character id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search character
  /character/search:
    get:
      tags:
        - characters
      summary: Search character
      parameters:
        - name: name
          in: query
          description: character name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
