tags:
  - name: characters
    description: characters API
  - name: clans
    description: clans API

paths:
  # [GET] all characters
  /character:
    get:
      tags:
        - characters
      summary: Get all characters
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of characters
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] character by id
  /character/{id}:
    get:
      tags:
        - characters
      summary: Get character by id
      parameters:
        - name: id
          in: path
          description: character id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search character
  /character/search:
    get:
      tags:
        - characters
      summary: Search character
      parameters:
        - name: name
          in: query
          description: character name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all clans
  /clan:
    get:
      tags:
        - clans
      summary: Get all clans
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of clans
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] clan by id
  /clan/{id}:
    get:
      tags:
        - clans
      summary: Get clan by id
      parameters:
        - name: id
          in: path
          description: clan id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search clan
  /clan/search:
    get:
      tags:
        - clans
      summary: Search clan
      parameters:
        - name: name
          in: query
          description: clan name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] all akatsuki members
  /akatsuki:
    get:
      tags:
        - akatsuki
      summary: Get all akatsuki members
      parameters:
        - name: page
          in: query
          description: Page no.
          type: string
        - name: limit
          in: query
          description: No. of akatsuki members
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] akatsuki member by id
  /akatsuki/{id}:
    get:
      tags:
        - akatsuki
      summary: Get akatsuki member by id
      parameters:
        - name: id
          in: path
          description: akatsuki id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] search akatsuki member
  /akatsuki/search:
    get:
      tags:
        - akatsuki
      summary: Search akatsuki member
      parameters:
        - name: name
          in: query
          description: akatsuki member name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
